apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"rapid-tanker-user-service"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"rapid-tanker-user-service"}]},"modified":true}'
    autopilot.gke.io/warden-version: 2.7.52
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"autopilot.gke.io/resource-adjustment":"{\"input\":{\"containers\":[{\"name\":\"rapid-tanker-user-service\"}]},\"output\":{\"containers\":[{\"limits\":{\"cpu\":\"500m\",\"ephemeral-storage\":\"1Gi\",\"memory\":\"2Gi\"},\"requests\":{\"cpu\":\"500m\",\"ephemeral-storage\":\"1Gi\",\"memory\":\"2Gi\"},\"name\":\"rapid-tanker-user-service\"}]},\"modified\":true}","autopilot.gke.io/warden-version":"2.7.52","deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2024-03-22T06:39:26Z","generation":1,"labels":{"app":"user"},"name":"user","namespace":"default","resourceVersion":"1013405","uid":"6c746f62-dc19-4791-9a09-effed8ea50c0"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"user"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"user"}},"spec":{"containers":[{"env":[{"name":"HOST_NAME","value":"rapid-tanker-config-server"},{"name":"NAMING_SERVER","value":"rapid-tanker-naming-server"},{"name":"DATABASE_URL","value":"mysql://avnadmin:AVNS_7KM2EK2K40M9zbZ9nYm@rapid-tanker-macharya914-26e5.a.aivencloud.com:13736/defaultdb?ssl-mode=REQUIRED"},{"name":"DATABASE_USERNAME","value":"root"},{"name":"DATABASE_PASSWORD","value":"roots"}],"image":"manojmdocker14/rapid-tanker-user-service:0.0.1-SNAPSHOT","imagePullPolicy":"IfNotPresent","name":"rapid-tanker-user-service","resources":{"limits":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"1Gi"},"requests":{"cpu":"250m","ephemeral-storage":"1Gi","memory":"1Gi"}},"securityContext":{"capabilities":{"drop":["NET_RAW"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"seccompProfile":{"type":"RuntimeDefault"}},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"kubernetes.io/arch","operator":"Equal","value":"amd64"}]}}},"status":{"conditions":[{"lastTransitionTime":"2024-03-22T06:39:26Z","lastUpdateTime":"2024-03-22T06:39:26Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2024-03-22T06:39:26Z","lastUpdateTime":"2024-03-22T06:39:26Z","message":"ReplicaSet \"user-c977cd794\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
  creationTimestamp: "2024-03-22T07:21:19Z"
  generation: 3
  labels:
    app: user
  name: user
  namespace: default
  resourceVersion: "1050802"
  uid: 7dd1a62d-f21f-4844-b274-3667b56a3fe8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-03-22T13:02:10+05:30"
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
        - env:
            - name: HOST_NAME
              value: rapid-tanker-config-server
            - name: NAMING_SERVER
              value: rapid-tanker-naming-server
            - name: DATABASE_URL
              value: ""
            - name: DATABASE_USERNAME
              value: ""
            - name: DATABASE_PASSWORD
              value: ""
          image: manojmdocker14/rapid-tanker-user-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: rapid-tanker-user-service
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 1Gi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 1Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-03-22T07:21:19Z"
      lastUpdateTime: "2024-03-22T07:32:13Z"
      message: ReplicaSet "user-c659c87dd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2024-03-22T07:33:08Z"
      lastUpdateTime: "2024-03-22T07:33:08Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
